package com.easypay.cornucopiaallqrpay.dal.pojo;

import java.util.Date;

public class TGoodsOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.trans_date
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private String transDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.sqe_id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private String sqeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.Goods_Order_Id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private String goodsOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.Amount
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.Mch_Id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.Pay_Order_Id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private String payOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.trans_state
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private Byte transState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.resp_code
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private String respCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.resp_desc
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private String respDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.CreateTime
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.UpdateTime
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.id
     *
     * @return the value of t_goods_order.id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.id
     *
     * @param id the value for t_goods_order.id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.trans_date
     *
     * @return the value of t_goods_order.trans_date
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public String getTransDate() {
        return transDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.trans_date
     *
     * @param transDate the value for t_goods_order.trans_date
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setTransDate(String transDate) {
        this.transDate = transDate == null ? null : transDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.sqe_id
     *
     * @return the value of t_goods_order.sqe_id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public String getSqeId() {
        return sqeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.sqe_id
     *
     * @param sqeId the value for t_goods_order.sqe_id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setSqeId(String sqeId) {
        this.sqeId = sqeId == null ? null : sqeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.Goods_Order_Id
     *
     * @return the value of t_goods_order.Goods_Order_Id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public String getGoodsOrderId() {
        return goodsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.Goods_Order_Id
     *
     * @param goodsOrderId the value for t_goods_order.Goods_Order_Id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setGoodsOrderId(String goodsOrderId) {
        this.goodsOrderId = goodsOrderId == null ? null : goodsOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.Amount
     *
     * @return the value of t_goods_order.Amount
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.Amount
     *
     * @param amount the value for t_goods_order.Amount
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.Mch_Id
     *
     * @return the value of t_goods_order.Mch_Id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.Mch_Id
     *
     * @param mchId the value for t_goods_order.Mch_Id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.Pay_Order_Id
     *
     * @return the value of t_goods_order.Pay_Order_Id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.Pay_Order_Id
     *
     * @param payOrderId the value for t_goods_order.Pay_Order_Id
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId == null ? null : payOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.trans_state
     *
     * @return the value of t_goods_order.trans_state
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public Byte getTransState() {
        return transState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.trans_state
     *
     * @param transState the value for t_goods_order.trans_state
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setTransState(Byte transState) {
        this.transState = transState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.resp_code
     *
     * @return the value of t_goods_order.resp_code
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.resp_code
     *
     * @param respCode the value for t_goods_order.resp_code
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setRespCode(String respCode) {
        this.respCode = respCode == null ? null : respCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.resp_desc
     *
     * @return the value of t_goods_order.resp_desc
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public String getRespDesc() {
        return respDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.resp_desc
     *
     * @param respDesc the value for t_goods_order.resp_desc
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setRespDesc(String respDesc) {
        this.respDesc = respDesc == null ? null : respDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.CreateTime
     *
     * @return the value of t_goods_order.CreateTime
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.CreateTime
     *
     * @param createtime the value for t_goods_order.CreateTime
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.UpdateTime
     *
     * @return the value of t_goods_order.UpdateTime
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.UpdateTime
     *
     * @param updatetime the value for t_goods_order.UpdateTime
     *
     * @mbggenerated Wed Apr 15 22:26:00 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}