package com.easypay.cornucopiaallqrpay.dal.pojo;

import java.util.Date;

public class TMchNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.id
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.trans_date
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private String transDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.sqe_id
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private String sqeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.Order_Id
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.MchId
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private String mchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.Mch_Order_No
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private String mchOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.OrderType
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private String ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.NotifyUrl
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private String notifyurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.NotifyCount
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private Byte notifycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.Result
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.Status
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.LastNotifyTime
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private Date lastnotifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.CreateTime
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_notify.UpdateTime
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.id
     *
     * @return the value of t_mch_notify.id
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.id
     *
     * @param id the value for t_mch_notify.id
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.trans_date
     *
     * @return the value of t_mch_notify.trans_date
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public String getTransDate() {
        return transDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.trans_date
     *
     * @param transDate the value for t_mch_notify.trans_date
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setTransDate(String transDate) {
        this.transDate = transDate == null ? null : transDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.sqe_id
     *
     * @return the value of t_mch_notify.sqe_id
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public String getSqeId() {
        return sqeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.sqe_id
     *
     * @param sqeId the value for t_mch_notify.sqe_id
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setSqeId(String sqeId) {
        this.sqeId = sqeId == null ? null : sqeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.Order_Id
     *
     * @return the value of t_mch_notify.Order_Id
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.Order_Id
     *
     * @param orderId the value for t_mch_notify.Order_Id
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.MchId
     *
     * @return the value of t_mch_notify.MchId
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public String getMchid() {
        return mchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.MchId
     *
     * @param mchid the value for t_mch_notify.MchId
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setMchid(String mchid) {
        this.mchid = mchid == null ? null : mchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.Mch_Order_No
     *
     * @return the value of t_mch_notify.Mch_Order_No
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public String getMchOrderNo() {
        return mchOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.Mch_Order_No
     *
     * @param mchOrderNo the value for t_mch_notify.Mch_Order_No
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setMchOrderNo(String mchOrderNo) {
        this.mchOrderNo = mchOrderNo == null ? null : mchOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.OrderType
     *
     * @return the value of t_mch_notify.OrderType
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public String getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.OrderType
     *
     * @param ordertype the value for t_mch_notify.OrderType
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype == null ? null : ordertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.NotifyUrl
     *
     * @return the value of t_mch_notify.NotifyUrl
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public String getNotifyurl() {
        return notifyurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.NotifyUrl
     *
     * @param notifyurl the value for t_mch_notify.NotifyUrl
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setNotifyurl(String notifyurl) {
        this.notifyurl = notifyurl == null ? null : notifyurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.NotifyCount
     *
     * @return the value of t_mch_notify.NotifyCount
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public Byte getNotifycount() {
        return notifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.NotifyCount
     *
     * @param notifycount the value for t_mch_notify.NotifyCount
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setNotifycount(Byte notifycount) {
        this.notifycount = notifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.Result
     *
     * @return the value of t_mch_notify.Result
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.Result
     *
     * @param result the value for t_mch_notify.Result
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.Status
     *
     * @return the value of t_mch_notify.Status
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.Status
     *
     * @param status the value for t_mch_notify.Status
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.LastNotifyTime
     *
     * @return the value of t_mch_notify.LastNotifyTime
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public Date getLastnotifytime() {
        return lastnotifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.LastNotifyTime
     *
     * @param lastnotifytime the value for t_mch_notify.LastNotifyTime
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setLastnotifytime(Date lastnotifytime) {
        this.lastnotifytime = lastnotifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.CreateTime
     *
     * @return the value of t_mch_notify.CreateTime
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.CreateTime
     *
     * @param createtime the value for t_mch_notify.CreateTime
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_notify.UpdateTime
     *
     * @return the value of t_mch_notify.UpdateTime
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_notify.UpdateTime
     *
     * @param updatetime the value for t_mch_notify.UpdateTime
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}