package com.easypay.cornucopiaallqrpay.dal.pojo;

import java.util.Date;

public class TMchInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_info.MchId
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String mchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_info.Name
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_info.Type
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_info.ReqKey
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String reqkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_info.ResKey
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String reskey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_info.State
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_info.CreateTime
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mch_info.UpdateTime
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_info.MchId
     *
     * @return the value of t_mch_info.MchId
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getMchid() {
        return mchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_info.MchId
     *
     * @param mchid the value for t_mch_info.MchId
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setMchid(String mchid) {
        this.mchid = mchid == null ? null : mchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_info.Name
     *
     * @return the value of t_mch_info.Name
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_info.Name
     *
     * @param name the value for t_mch_info.Name
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_info.Type
     *
     * @return the value of t_mch_info.Type
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_info.Type
     *
     * @param type the value for t_mch_info.Type
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_info.ReqKey
     *
     * @return the value of t_mch_info.ReqKey
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getReqkey() {
        return reqkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_info.ReqKey
     *
     * @param reqkey the value for t_mch_info.ReqKey
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setReqkey(String reqkey) {
        this.reqkey = reqkey == null ? null : reqkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_info.ResKey
     *
     * @return the value of t_mch_info.ResKey
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getReskey() {
        return reskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_info.ResKey
     *
     * @param reskey the value for t_mch_info.ResKey
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setReskey(String reskey) {
        this.reskey = reskey == null ? null : reskey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_info.State
     *
     * @return the value of t_mch_info.State
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_info.State
     *
     * @param state the value for t_mch_info.State
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_info.CreateTime
     *
     * @return the value of t_mch_info.CreateTime
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_info.CreateTime
     *
     * @param createtime the value for t_mch_info.CreateTime
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mch_info.UpdateTime
     *
     * @return the value of t_mch_info.UpdateTime
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mch_info.UpdateTime
     *
     * @param updatetime the value for t_mch_info.UpdateTime
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}