package com.easypay.cornucopiaallqrpay.dal.pojo;

import java.util.Date;

public class TPayOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.trans_date
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String transDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.sqe_id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String sqeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Pay_Order_Id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String payOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Mch_Id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.mch_order_id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String mchOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Channel_Id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Amount
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Currency
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Status
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Client_Ip
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String clientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Device
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.device_Sn
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String deviceSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Subject
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Body
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Extra
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.ChannelMchId
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String channelmchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.ChannelOrderNo
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String channelorderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.ErrCode
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String errcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.ErrMsg
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String errmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Param1
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String param1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Param2
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private String param2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.ExpireTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private Long expiretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.PaySuccTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private Long paysucctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.CreateTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.UpdateTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.id
     *
     * @return the value of t_pay_order.id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.id
     *
     * @param id the value for t_pay_order.id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.trans_date
     *
     * @return the value of t_pay_order.trans_date
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getTransDate() {
        return transDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.trans_date
     *
     * @param transDate the value for t_pay_order.trans_date
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setTransDate(String transDate) {
        this.transDate = transDate == null ? null : transDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.sqe_id
     *
     * @return the value of t_pay_order.sqe_id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getSqeId() {
        return sqeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.sqe_id
     *
     * @param sqeId the value for t_pay_order.sqe_id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setSqeId(String sqeId) {
        this.sqeId = sqeId == null ? null : sqeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Pay_Order_Id
     *
     * @return the value of t_pay_order.Pay_Order_Id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Pay_Order_Id
     *
     * @param payOrderId the value for t_pay_order.Pay_Order_Id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId == null ? null : payOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Mch_Id
     *
     * @return the value of t_pay_order.Mch_Id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Mch_Id
     *
     * @param mchId the value for t_pay_order.Mch_Id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.mch_order_id
     *
     * @return the value of t_pay_order.mch_order_id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getMchOrderId() {
        return mchOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.mch_order_id
     *
     * @param mchOrderId the value for t_pay_order.mch_order_id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setMchOrderId(String mchOrderId) {
        this.mchOrderId = mchOrderId == null ? null : mchOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Channel_Id
     *
     * @return the value of t_pay_order.Channel_Id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Channel_Id
     *
     * @param channelId the value for t_pay_order.Channel_Id
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Amount
     *
     * @return the value of t_pay_order.Amount
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Amount
     *
     * @param amount the value for t_pay_order.Amount
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Currency
     *
     * @return the value of t_pay_order.Currency
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Currency
     *
     * @param currency the value for t_pay_order.Currency
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Status
     *
     * @return the value of t_pay_order.Status
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Status
     *
     * @param status the value for t_pay_order.Status
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Client_Ip
     *
     * @return the value of t_pay_order.Client_Ip
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Client_Ip
     *
     * @param clientIp the value for t_pay_order.Client_Ip
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Device
     *
     * @return the value of t_pay_order.Device
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Device
     *
     * @param device the value for t_pay_order.Device
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.device_Sn
     *
     * @return the value of t_pay_order.device_Sn
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getDeviceSn() {
        return deviceSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.device_Sn
     *
     * @param deviceSn the value for t_pay_order.device_Sn
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setDeviceSn(String deviceSn) {
        this.deviceSn = deviceSn == null ? null : deviceSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Subject
     *
     * @return the value of t_pay_order.Subject
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Subject
     *
     * @param subject the value for t_pay_order.Subject
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Body
     *
     * @return the value of t_pay_order.Body
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Body
     *
     * @param body the value for t_pay_order.Body
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Extra
     *
     * @return the value of t_pay_order.Extra
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Extra
     *
     * @param extra the value for t_pay_order.Extra
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.ChannelMchId
     *
     * @return the value of t_pay_order.ChannelMchId
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getChannelmchid() {
        return channelmchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.ChannelMchId
     *
     * @param channelmchid the value for t_pay_order.ChannelMchId
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setChannelmchid(String channelmchid) {
        this.channelmchid = channelmchid == null ? null : channelmchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.ChannelOrderNo
     *
     * @return the value of t_pay_order.ChannelOrderNo
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getChannelorderno() {
        return channelorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.ChannelOrderNo
     *
     * @param channelorderno the value for t_pay_order.ChannelOrderNo
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setChannelorderno(String channelorderno) {
        this.channelorderno = channelorderno == null ? null : channelorderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.ErrCode
     *
     * @return the value of t_pay_order.ErrCode
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getErrcode() {
        return errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.ErrCode
     *
     * @param errcode the value for t_pay_order.ErrCode
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setErrcode(String errcode) {
        this.errcode = errcode == null ? null : errcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.ErrMsg
     *
     * @return the value of t_pay_order.ErrMsg
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getErrmsg() {
        return errmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.ErrMsg
     *
     * @param errmsg the value for t_pay_order.ErrMsg
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setErrmsg(String errmsg) {
        this.errmsg = errmsg == null ? null : errmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Param1
     *
     * @return the value of t_pay_order.Param1
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getParam1() {
        return param1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Param1
     *
     * @param param1 the value for t_pay_order.Param1
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setParam1(String param1) {
        this.param1 = param1 == null ? null : param1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Param2
     *
     * @return the value of t_pay_order.Param2
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public String getParam2() {
        return param2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Param2
     *
     * @param param2 the value for t_pay_order.Param2
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setParam2(String param2) {
        this.param2 = param2 == null ? null : param2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.ExpireTime
     *
     * @return the value of t_pay_order.ExpireTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public Long getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.ExpireTime
     *
     * @param expiretime the value for t_pay_order.ExpireTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setExpiretime(Long expiretime) {
        this.expiretime = expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.PaySuccTime
     *
     * @return the value of t_pay_order.PaySuccTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public Long getPaysucctime() {
        return paysucctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.PaySuccTime
     *
     * @param paysucctime the value for t_pay_order.PaySuccTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setPaysucctime(Long paysucctime) {
        this.paysucctime = paysucctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.CreateTime
     *
     * @return the value of t_pay_order.CreateTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.CreateTime
     *
     * @param createtime the value for t_pay_order.CreateTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.UpdateTime
     *
     * @return the value of t_pay_order.UpdateTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.UpdateTime
     *
     * @param updatetime the value for t_pay_order.UpdateTime
     *
     * @mbggenerated Mon May 04 17:04:08 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}