package com.easypay.cornucopiaallqrpay.dal.pojo;

import java.util.Date;

public class TPayOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Pay_Order_Id
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String payOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Mch_Id
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Mch_Order_No
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String mchOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Channel_Id
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Amount
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Currency
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Status
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Client_Ip
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String clientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Device
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Subject
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Body
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Extra
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.ChannelMchId
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String channelmchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.ChannelOrderNo
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String channelorderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.ErrCode
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String errcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.ErrMsg
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String errmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Param1
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String param1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Param2
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String param2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.Notify_Url
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.NotifyCount
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private Byte notifycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.LastNotifyTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private Long lastnotifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.ExpireTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private Long expiretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.PaySuccTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private Long paysucctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.CreateTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.UpdateTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Pay_Order_Id
     *
     * @return the value of t_pay_order.Pay_Order_Id
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Pay_Order_Id
     *
     * @param payOrderId the value for t_pay_order.Pay_Order_Id
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId == null ? null : payOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Mch_Id
     *
     * @return the value of t_pay_order.Mch_Id
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Mch_Id
     *
     * @param mchId the value for t_pay_order.Mch_Id
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Mch_Order_No
     *
     * @return the value of t_pay_order.Mch_Order_No
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getMchOrderNo() {
        return mchOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Mch_Order_No
     *
     * @param mchOrderNo the value for t_pay_order.Mch_Order_No
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setMchOrderNo(String mchOrderNo) {
        this.mchOrderNo = mchOrderNo == null ? null : mchOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Channel_Id
     *
     * @return the value of t_pay_order.Channel_Id
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Channel_Id
     *
     * @param channelId the value for t_pay_order.Channel_Id
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Amount
     *
     * @return the value of t_pay_order.Amount
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Amount
     *
     * @param amount the value for t_pay_order.Amount
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Currency
     *
     * @return the value of t_pay_order.Currency
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Currency
     *
     * @param currency the value for t_pay_order.Currency
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Status
     *
     * @return the value of t_pay_order.Status
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Status
     *
     * @param status the value for t_pay_order.Status
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Client_Ip
     *
     * @return the value of t_pay_order.Client_Ip
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Client_Ip
     *
     * @param clientIp the value for t_pay_order.Client_Ip
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Device
     *
     * @return the value of t_pay_order.Device
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Device
     *
     * @param device the value for t_pay_order.Device
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Subject
     *
     * @return the value of t_pay_order.Subject
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Subject
     *
     * @param subject the value for t_pay_order.Subject
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Body
     *
     * @return the value of t_pay_order.Body
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Body
     *
     * @param body the value for t_pay_order.Body
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Extra
     *
     * @return the value of t_pay_order.Extra
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Extra
     *
     * @param extra the value for t_pay_order.Extra
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.ChannelMchId
     *
     * @return the value of t_pay_order.ChannelMchId
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getChannelmchid() {
        return channelmchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.ChannelMchId
     *
     * @param channelmchid the value for t_pay_order.ChannelMchId
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setChannelmchid(String channelmchid) {
        this.channelmchid = channelmchid == null ? null : channelmchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.ChannelOrderNo
     *
     * @return the value of t_pay_order.ChannelOrderNo
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getChannelorderno() {
        return channelorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.ChannelOrderNo
     *
     * @param channelorderno the value for t_pay_order.ChannelOrderNo
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setChannelorderno(String channelorderno) {
        this.channelorderno = channelorderno == null ? null : channelorderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.ErrCode
     *
     * @return the value of t_pay_order.ErrCode
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getErrcode() {
        return errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.ErrCode
     *
     * @param errcode the value for t_pay_order.ErrCode
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setErrcode(String errcode) {
        this.errcode = errcode == null ? null : errcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.ErrMsg
     *
     * @return the value of t_pay_order.ErrMsg
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getErrmsg() {
        return errmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.ErrMsg
     *
     * @param errmsg the value for t_pay_order.ErrMsg
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setErrmsg(String errmsg) {
        this.errmsg = errmsg == null ? null : errmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Param1
     *
     * @return the value of t_pay_order.Param1
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getParam1() {
        return param1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Param1
     *
     * @param param1 the value for t_pay_order.Param1
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setParam1(String param1) {
        this.param1 = param1 == null ? null : param1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Param2
     *
     * @return the value of t_pay_order.Param2
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getParam2() {
        return param2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Param2
     *
     * @param param2 the value for t_pay_order.Param2
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setParam2(String param2) {
        this.param2 = param2 == null ? null : param2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.Notify_Url
     *
     * @return the value of t_pay_order.Notify_Url
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.Notify_Url
     *
     * @param notifyUrl the value for t_pay_order.Notify_Url
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.NotifyCount
     *
     * @return the value of t_pay_order.NotifyCount
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public Byte getNotifycount() {
        return notifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.NotifyCount
     *
     * @param notifycount the value for t_pay_order.NotifyCount
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setNotifycount(Byte notifycount) {
        this.notifycount = notifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.LastNotifyTime
     *
     * @return the value of t_pay_order.LastNotifyTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public Long getLastnotifytime() {
        return lastnotifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.LastNotifyTime
     *
     * @param lastnotifytime the value for t_pay_order.LastNotifyTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setLastnotifytime(Long lastnotifytime) {
        this.lastnotifytime = lastnotifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.ExpireTime
     *
     * @return the value of t_pay_order.ExpireTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public Long getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.ExpireTime
     *
     * @param expiretime the value for t_pay_order.ExpireTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setExpiretime(Long expiretime) {
        this.expiretime = expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.PaySuccTime
     *
     * @return the value of t_pay_order.PaySuccTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public Long getPaysucctime() {
        return paysucctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.PaySuccTime
     *
     * @param paysucctime the value for t_pay_order.PaySuccTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setPaysucctime(Long paysucctime) {
        this.paysucctime = paysucctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.CreateTime
     *
     * @return the value of t_pay_order.CreateTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.CreateTime
     *
     * @param createtime the value for t_pay_order.CreateTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.UpdateTime
     *
     * @return the value of t_pay_order.UpdateTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.UpdateTime
     *
     * @param updatetime the value for t_pay_order.UpdateTime
     *
     * @mbggenerated Sun Apr 05 13:41:50 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}