package com.easypay.cornucopiaallqrpay.dal.pojo;

import java.util.Date;

public class UserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.user_id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.user_state
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    private Integer userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.login_id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.login_id_mask
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    private String loginIdMask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.login_pswd
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    private String loginPswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.open_id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.user_from
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    private Integer userFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.create_time
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.update_time
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.id
     *
     * @return the value of user_login.id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.id
     *
     * @param id the value for user_login.id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.user_id
     *
     * @return the value of user_login.user_id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.user_id
     *
     * @param userId the value for user_login.user_id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.user_state
     *
     * @return the value of user_login.user_state
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public Integer getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.user_state
     *
     * @param userState the value for user_login.user_state
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.login_id
     *
     * @return the value of user_login.login_id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.login_id
     *
     * @param loginId the value for user_login.login_id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.login_id_mask
     *
     * @return the value of user_login.login_id_mask
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public String getLoginIdMask() {
        return loginIdMask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.login_id_mask
     *
     * @param loginIdMask the value for user_login.login_id_mask
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public void setLoginIdMask(String loginIdMask) {
        this.loginIdMask = loginIdMask == null ? null : loginIdMask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.login_pswd
     *
     * @return the value of user_login.login_pswd
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public String getLoginPswd() {
        return loginPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.login_pswd
     *
     * @param loginPswd the value for user_login.login_pswd
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public void setLoginPswd(String loginPswd) {
        this.loginPswd = loginPswd == null ? null : loginPswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.open_id
     *
     * @return the value of user_login.open_id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.open_id
     *
     * @param openId the value for user_login.open_id
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.user_from
     *
     * @return the value of user_login.user_from
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public Integer getUserFrom() {
        return userFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.user_from
     *
     * @param userFrom the value for user_login.user_from
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public void setUserFrom(Integer userFrom) {
        this.userFrom = userFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.create_time
     *
     * @return the value of user_login.create_time
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.create_time
     *
     * @param createTime the value for user_login.create_time
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.update_time
     *
     * @return the value of user_login.update_time
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.update_time
     *
     * @param updateTime the value for user_login.update_time
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}