package com.easypay.cornucopiaallqrpay.dal.pojo;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_level
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private Integer userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.legal_name
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String legalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id_no
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id_no_mask
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String idNoMask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id_photo_f
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String idPhotoF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id_photo_b
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String idPhotoB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_level
     *
     * @return the value of user_info.user_level
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public Integer getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_level
     *
     * @param userLevel the value for user_info.user_level
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.legal_name
     *
     * @return the value of user_info.legal_name
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getLegalName() {
        return legalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.legal_name
     *
     * @param legalName the value for user_info.legal_name
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setLegalName(String legalName) {
        this.legalName = legalName == null ? null : legalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id_no
     *
     * @return the value of user_info.id_no
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id_no
     *
     * @param idNo the value for user_info.id_no
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id_no_mask
     *
     * @return the value of user_info.id_no_mask
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getIdNoMask() {
        return idNoMask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id_no_mask
     *
     * @param idNoMask the value for user_info.id_no_mask
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setIdNoMask(String idNoMask) {
        this.idNoMask = idNoMask == null ? null : idNoMask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id_photo_f
     *
     * @return the value of user_info.id_photo_f
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getIdPhotoF() {
        return idPhotoF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id_photo_f
     *
     * @param idPhotoF the value for user_info.id_photo_f
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setIdPhotoF(String idPhotoF) {
        this.idPhotoF = idPhotoF == null ? null : idPhotoF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id_photo_b
     *
     * @return the value of user_info.id_photo_b
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getIdPhotoB() {
        return idPhotoB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id_photo_b
     *
     * @param idPhotoB the value for user_info.id_photo_b
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setIdPhotoB(String idPhotoB) {
        this.idPhotoB = idPhotoB == null ? null : idPhotoB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}