package com.easypay.cornucopiaallqrpay.dal.pojo;

import java.util.Date;

public class UserMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_map.id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_map.user_id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_map.member_id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_map.member_level
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private String memberLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_map.create_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_map.update_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_map.id
     *
     * @return the value of user_map.id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_map.id
     *
     * @param id the value for user_map.id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_map.user_id
     *
     * @return the value of user_map.user_id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_map.user_id
     *
     * @param userId the value for user_map.user_id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_map.member_id
     *
     * @return the value of user_map.member_id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_map.member_id
     *
     * @param memberId the value for user_map.member_id
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_map.member_level
     *
     * @return the value of user_map.member_level
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public String getMemberLevel() {
        return memberLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_map.member_level
     *
     * @param memberLevel the value for user_map.member_level
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setMemberLevel(String memberLevel) {
        this.memberLevel = memberLevel == null ? null : memberLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_map.create_time
     *
     * @return the value of user_map.create_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_map.create_time
     *
     * @param createTime the value for user_map.create_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_map.update_time
     *
     * @return the value of user_map.update_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_map.update_time
     *
     * @param updateTime the value for user_map.update_time
     *
     * @mbggenerated Sun Mar 22 20:21:27 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}