#数据源
spring:
  #profiles: prod
  datasource:
    url: jdbc:mysql://47.98.210.13:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource #druid数据源
mybatis:
  configuration:
    #开启驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/easypay/cornucopiaquery/dal/**/*.xml #xml文件内容
  type-aliases-package: com.easypay.cornucopiaquery.dal.pojo #实体类包
server:
  port: 8081