package com.easypay.cornucopiatrans.dal.dao;

import com.easypay.cornucopiatrans.dal.pojo.UserCardSettle;

public interface UserCardSettleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_settle
     *
     * @mbggenerated Sun Mar 15 19:33:54 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_settle
     *
     * @mbggenerated Sun Mar 15 19:33:54 CST 2020
     */
    int insert(UserCardSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_settle
     *
     * @mbggenerated Sun Mar 15 19:33:54 CST 2020
     */
    int insertSelective(UserCardSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_settle
     *
     * @mbggenerated Sun Mar 15 19:33:54 CST 2020
     */
    UserCardSettle selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_settle
     *
     * @mbggenerated Sun Mar 15 19:33:54 CST 2020
     */
    int updateByPrimaryKeySelective(UserCardSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_settle
     *
     * @mbggenerated Sun Mar 15 19:33:54 CST 2020
     */
    int updateByPrimaryKey(UserCardSettle record);
}