server:
  servlet:
    context-path: /allqrpay
  port: 8082
  #数据源
spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    request-context-attribute: request
    content-type: text/html
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    cache: false
    charset: UTF-8
  datasource:
    url: jdbc:mysql://47.98.210.13:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource #druid数据源
mybatis:
  configuration:
    #开启驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/easypay/cornucopiaallqrpay/dal/**/*.xml #xml文件内容
  type-aliases-package: com.easypay.cornucopiaallqrpay.dal.pojo #实体类包

config:
  ali:
    notify_url: http://www.hoteonpay.com/allqrpay/notify/pay/aliPayNotifyRes.htm
    return_url: http://www.hoteonpay.com/allqrpay/payFinish.htm
  wx:
    certRootPath: D:\\huen
    notifyUrl: http://www.hoteonpay.com/allqrpay/notify/pay/wxPayNotifyRes.htm
#内部系统调用
myrsa:
  publickey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCNhKIYSGR9k7GDWz0NiDHBv2yoRBdYcMFVXpZG0d6XsuYUHCAnRpJC/jdOWDQYzWlKP4ZF+qFKHWyu8ihjEdIoMNBUlSnSS3VUedz+pHHnrxX+Tr5a9+cCMKgXMnHWyZo4Xc0QprLTicngH6vLtGvLSwkXuhrNwx/sfa5MzweJEwIDAQAB
  privatekey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAI2EohhIZH2TsYNbPQ2IMcG/bKhEF1hwwVVelkbR3pey5hQcICdGkkL+N05YNBjNaUo/hkX6oUodbK7yKGMR0igw0FSVKdJLdVR53P6kceevFf5Ovlr35wIwqBcycdbJmjhdzRCmstOJyeAfq8u0a8tLCRe6Gs3DH+x9rkzPB4kTAgMBAAECgYAni11kHa5+7KtYwkEALAODWUM6jbRcUT2k5kZlybVCfIoQKn/Nmcm7EKBRsxHzsEpwpemWWl+Bf1FkXWRtsogfqJn63FU6lhZmnsIqEssf6816v/LumH8C9rcWndt1R0YibJ7ob/VXWtLh7R+AoJKoYB01XQdg2QGvBSL4XGN/gQJBAOZowPbVruq/7aEIRx64JOOP6Z4Wi3XkZ4iTfB1DaPVNL7wIBrJF/CyjfZn2HZYeqM6tF7LAV7gk+hsBM5k568ECQQCdPG44Sy2+8THSZ03z1igTLNu0gRSrr/61hxce02/YljRrAj0ezI1T+e9HN4kvNksj60698ENnskv+h50K3HnTAkBStB8vepwCn0nIl5QPrsFu/WU53ZXJh2ayW14dkujFxCLyN19P9lcCHt0iunj8PZ0SModjHi9eZcdwkgnXYjcBAkAee/LakyjBVj3Ujxa76Y9HeHD4I/Z/+tUlGJXQ8ilDEowDGyICcKIN3+0WH5xHPP2Ab0SK6qQG3LiDFoPJ8UjlAkEApS6i1YCsfGb/B32FbfQ1282Gd6b8zEQVXkL05gL9TZp5xMROO4C/6GvEKhXilHyQCKc3p9KD4XdOKX1SoNpOfw==
#展示调用
frontrsa:
  publickey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC7/QhrSmmibvJnJXD27Bd9e9qDM1A1s2Z4nLhq3vGDAfO9fo5T+DTZKrH/VVv9uDUIQUfe2WciVALLVT1CocPqIaVjJ67DoZOVigYqEX1Au/o+5iP15r//QJJAS41f7JG+YagiOznQn5C2NlueFxeOl5TW9wHL8vtLO2KbCn9J3QIDAQAB
  privatekey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALv9CGtKaaJu8mclcPbsF3172oMzUDWzZnicuGre8YMB871+jlP4NNkqsf9VW/24NQhBR97ZZyJUAstVPUKhw+ohpWMnrsOhk5WKBioRfUC7+j7mI/Xmv/9AkkBLjV/skb5hqCI7OdCfkLY2W54XF46XlNb3Acvy+0s7YpsKf0ndAgMBAAECgYBgcrnXEh6QUAveD7+dcBO9NcYuei004A46421ap3eRl3bOShgLzNSQdu9L6SeBTPkoexW8qB3Z5vBoEhuUDBrPKlYQvKTmagfVV0JJB7x5p24YcSZdELtfvnVhEDc5p57lpKdoeuQ6eY/T/bC2ieEjRK96hTNNJmSsDdtDpQDFAQJBAPW5O8dHOj343qfFZVaxrKPsqTbuQHgegL+KSOi+XuaB0pow/VAHuNYVBsWMWMX3rN9vGH3jUEeGbdJ6CaoHxoUCQQDD2azOquDsW62xh1wSpRLQyqWWXjoJo/zgQOt3VSwIvOxM4NfKZA7pQpJIwbeAVNVPfC4FxjVOnhTg53XIdzF5AkEA72jbmmyGjYzl+xZzhwUzjL9vmwqFG8O0c2qbYNDii7nfZMXoeModR9BSubTlZXTMJSIL/dO1CwsqA1FOCzDqNQJAZt6TxO2+PIefAQtfEjAAZQi71vJhO6UV8thGlaR3/5Lz7yF+VsEdj+m2ml6duttUO263YbMNVuDziHoqxIPOyQJAZdYKfd0JZ3eSE933lRQKW1qAMi3OqSusvJBBeSFnEvJFMBEGsitGVKcIHjT1ZoMmU09Stm4tfdh6MT9DLjPOJA==

baseUrl: http://127.0.0.1:8082/allqrpay