package com.easypay.cornucopiaallqrpay.dal.dao;

import com.easypay.cornucopiaallqrpay.dal.pojo.TMchInfo;

public interface TMchInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mch_info
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mch_info
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    int insert(TMchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mch_info
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    int insertSelective(TMchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mch_info
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    TMchInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mch_info
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    int updateByPrimaryKeySelective(TMchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mch_info
     *
     * @mbggenerated Tue May 05 14:54:12 CST 2020
     */
    int updateByPrimaryKey(TMchInfo record);
}