package com.easypay.cornucopiaallqrpay.dal.dao;

import com.easypay.cornucopiaallqrpay.dal.pojo.TPayChannel;
import com.easypay.cornucopiaallqrpay.dal.pojo.TPayChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPayChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_channel
     *
     * @mbggenerated Wed Apr 22 21:39:18 CST 2020
     */
    int countByExample(TPayChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_channel
     *
     * @mbggenerated Wed Apr 22 21:39:18 CST 2020
     */
    int deleteByExample(TPayChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_channel
     *
     * @mbggenerated Wed Apr 22 21:39:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_channel
     *
     * @mbggenerated Wed Apr 22 21:39:18 CST 2020
     */
    int insert(TPayChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_channel
     *
     * @mbggenerated Wed Apr 22 21:39:18 CST 2020
     */
    int insertSelective(TPayChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_channel
     *
     * @mbggenerated Wed Apr 22 21:39:18 CST 2020
     */
    List<TPayChannel> selectByExample(TPayChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_channel
     *
     * @mbggenerated Wed Apr 22 21:39:18 CST 2020
     */
    TPayChannel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_channel
     *
     * @mbggenerated Wed Apr 22 21:39:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") TPayChannel record, @Param("example") TPayChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_channel
     *
     * @mbggenerated Wed Apr 22 21:39:18 CST 2020
     */
    int updateByExample(@Param("record") TPayChannel record, @Param("example") TPayChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_channel
     *
     * @mbggenerated Wed Apr 22 21:39:18 CST 2020
     */
    int updateByPrimaryKeySelective(TPayChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_channel
     *
     * @mbggenerated Wed Apr 22 21:39:18 CST 2020
     */
    int updateByPrimaryKey(TPayChannel record);
}