package com.easypay.cornucopiaallqrpay.dal.dao;

import com.easypay.cornucopiaallqrpay.dal.pojo.TPayOrder;
import com.easypay.cornucopiaallqrpay.dal.pojo.TPayOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPayOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbggenerated Sun Apr 19 15:46:43 CST 2020
     */
    int countByExample(TPayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbggenerated Sun Apr 19 15:46:43 CST 2020
     */
    int deleteByExample(TPayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbggenerated Sun Apr 19 15:46:43 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbggenerated Sun Apr 19 15:46:43 CST 2020
     */
    int insert(TPayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbggenerated Sun Apr 19 15:46:43 CST 2020
     */
    int insertSelective(TPayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbggenerated Sun Apr 19 15:46:43 CST 2020
     */
    List<TPayOrder> selectByExample(TPayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbggenerated Sun Apr 19 15:46:43 CST 2020
     */
    TPayOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbggenerated Sun Apr 19 15:46:43 CST 2020
     */
    int updateByExampleSelective(@Param("record") TPayOrder record, @Param("example") TPayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbggenerated Sun Apr 19 15:46:43 CST 2020
     */
    int updateByExample(@Param("record") TPayOrder record, @Param("example") TPayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbggenerated Sun Apr 19 15:46:43 CST 2020
     */
    int updateByPrimaryKeySelective(TPayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbggenerated Sun Apr 19 15:46:43 CST 2020
     */
    int updateByPrimaryKey(TPayOrder record);
}