package com.easypay.cornucopiaallqrpay.dal.dao;

import com.easypay.cornucopiaallqrpay.dal.pojo.TransOrdInfo;

public interface TransOrdInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_ord_info
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_ord_info
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    int insert(TransOrdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_ord_info
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    int insertSelective(TransOrdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_ord_info
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    TransOrdInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_ord_info
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    int updateByPrimaryKeySelective(TransOrdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_ord_info
     *
     * @mbggenerated Sat Apr 11 14:55:49 CST 2020
     */
    int updateByPrimaryKey(TransOrdInfo record);
}